// src/domain/types.ts

/**
 * Current state of an abandoned-checkout recovery.
 *
 * This state is an important input into agent behaviour.
 */
export type CheckoutRecoveryStatus =
  | "DETECTED"
  | "MESSAGE_SENT"
  | "ENGAGED"
  | "COMPLETED"
  | "EXPIRED"
  | "PENDING"
  | "RECOVERED"
  | "CANCELLED";


/**
 * The purpose/context of a conversation associated
 * with a checkout recovery.
 */
export type ConversationType =
  | "RECOVERY"
  | "FOLLOW_UP"
  | "POST_PURCHASE"
  | "PRODUCT_DISCOVERY"
  | "PRODUCT_SUPPORT"
  | "SUPPORT";


/**
 * Direction of a message relative to Moda Interact.
 */
export type MessageDirection =
  | "INBOUND"
  | "OUTBOUND";


/**
 * Who actually produced the message.
 *
 * This is deliberately different from MessageDirection.
 *
 * AUTOMATION:
 *   abandoned-cart template etc.
 *
 * AGENT:
 *   generated by the commerce agent.
 *
 * HUMAN:
 *   future human support/operator.
 *
 * CUSTOMER:
 *   the Shopify customer.
 */
export type MessageSenderType =
  | "CUSTOMER"
  | "AUTOMATION"
  | "AGENT"
  | "HUMAN";


/**
 * Delivery lifecycle of a WhatsApp message.
 */
export type MessageStatus =
  | "PENDING"
  | "SENT"
  | "DELIVERED"
  | "READ"
  | "FAILED";


/**
 * Domain representation of a customer.
 *
 * A customer belongs to a Shopify store.
 * The same phone number can therefore exist as a different
 * customer for different stores.
 */
export interface CustomerContext {
  id: string;
  shop: string;

  phone: string | null;
  email: string | null;

  firstName: string | null;
  lastName: string | null;

  shopifyCustomerId: string | null;
}


/**
 * Domain representation of a checkout recovery.
 *
 * CheckoutRecovery is the main workflow state for the
 * abandoned-checkout process.
 */
export interface CheckoutRecoveryContext {
  id: string;

  shop: string;

  checkoutToken: string;
  cartToken: string | null;

  status: CheckoutRecoveryStatus;

  currency: string | null;
  totalPrice: string | null;

  checkoutUrl: string | null;

  detectedAt: Date;
  messageSentAt: Date | null;
  engagedAt: Date | null;
  completedAt: Date | null;
  expiredAt: Date | null;
}


/**
 * One persisted message within a conversation.
 */
export interface ConversationMessageContext {
  id: string;

  providerMessageId: string | null;
  inReplyToProviderId: string | null;

  direction: MessageDirection;
  senderType: MessageSenderType;
  status: MessageStatus;

  content: string;

  createdAt: Date;

  sentAt: Date | null;
  deliveredAt: Date | null;
  readAt: Date | null;
}


/**
 * Conversation belonging to a checkout recovery.
 *
 * Conversation contains interaction history.
 * CheckoutRecovery contains commercial/workflow state.
 */
export interface ConversationContext {
  id: string;

  type: ConversationType;

  inboundVersion: number;
  lastProcessedVersion: number;

  summary: string | null;

  lastInboundAt: Date | null;
  lastMessageAt: Date | null;

  messages: ConversationMessageContext[];
}


/**
 * Complete domain context supplied to the commerce agent.
 */
export interface RecoveryAgentContext {
  customer: CustomerContext | null;

  recovery: CheckoutRecoveryContext;

  conversation: ConversationContext;

  shop: string;
}

