import type { BackgroundRuntimeConfigSnapshot } from "../../src/runtime/background-runtime-config.js";

const defaults: BackgroundRuntimeConfigSnapshot = {
  id: "default",
  version: 0,
  billingReconciliationIntervalSeconds: 60,
  billingReconciliationShopBatchSize: 50,
  shopifyUsagePublishBatchSize: 50,
  recoveryRepairIntervalSeconds: 300,
  recoveryRepairShopBatchSize: 100,
  recoveryResumeBatchSize: 25,
  translationReconciliationIntervalSeconds: 300,
  translationBatchMaxRequests: 100,
  conversationQuietWindowMs: 3000,
  conversationMaxSettleWindowMs: 10000,
  billingFrozenRecheckSeconds: 3600,
  billingProviderRetrySeconds: 300,
  shopifyUsageRetryBaseSeconds: 60,
  shopifyUsageRetryMaxSeconds: 3600,
  translationReconciliationPageSize: 100,
  translationClaimTimeoutSeconds: 900,
  translationSubmitRetrySeconds: 300,
  translationInitialPollSeconds: 300,
  translationPollIntervalSeconds: 300,
  translationResultRetrySeconds: 300,
  translationSubmitMaxAttempts: 3,
  translationMaxAutoRetries: 3,
  rawSenderLimitPerMinute: 60,
  rawGlobalLimitPerMinute: 20000,
  turnSenderLimitPerMinute: 12,
  turnSenderLimitPerTenMinutes: 60,
  turnConversationLimitPerMinute: 12,
  turnConversationLimitPerTenMinutes: 60,
  turnShopLimitPerMinute: 600,
  turnGlobalLimitPerMinute: 5000,
  discoverySenderLimitPerMinute: 4,
  discoverySenderLimitPerTenMinutes: 12,
  discoveryConversationLimitPerMinute: 4,
  discoveryConversationLimitPerTenMinutes: 12,
  checkoutQueueGlobalConcurrency: 10,
  orderQueueGlobalConcurrency: 5,
  pendingRecoveryQueueGlobalConcurrency: 10,
  recoveryResumeQueueGlobalConcurrency: 10,
  whatsappQueueGlobalConcurrency: 20,
  merchantCommunicationsQueueGlobalConcurrency: 10,
  billingSubscriptionQueueGlobalConcurrency: 10,
  checkoutRecoveryLifetimeDays: 21,
  createdAt: new Date(0),
  updatedAt: new Date(0),
};

export function backgroundRuntimeConfig(
  overrides: Partial<BackgroundRuntimeConfigSnapshot> = {},
): BackgroundRuntimeConfigSnapshot {
  return { ...defaults, ...overrides };
}